config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :tvshows
  resources :tvshows do
    resource :seasons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_and_belongs_to_many :episodes 
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :season
  has_and_belongs_to_many :characters
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :tvshow
  has_many :episodes
end

app/models/tvshow.rb
class Tvshow < ActiveRecord::Base
  has_many :seasons
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
    # B
    @blackMirror = Tvshow.find_by(name: 'Black Mirror')
    @breakingBad = Tvshow.find_by(name: 'Breaking Bad')
    
    # G
    @gameOfThrones = Tvshow.find_by(name: 'Game of Thrones')
  end
  
  def about
  end
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  
  
  # GET request to /tvshows/:id
  def show
    @gameOfThrones = Tvshow.find_by(name: 'Game of Thrones')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <!-- Navigation bar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to '/', class: "navbar-brand" do %>
            <div id = "site-name-navbar">
              <i class="fa fa-film"></i>
              Episodewrap
            </div>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><button type="button" id = "btn-spoiler" class="btn btn-outline-warning">Spoiler Mode</button></li>
            <li><%= link_to "Series", '#' %></li>
            <li><%= link_to "About", '/about' %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <!-- End of navigation bar -->
    
    
    <%= yield %>
    
    
    <!-- Footer -->
    <footer class = 'footer text-center'>
      <div class = 'container'>
        <%= link_to "/", class: "footer-brand" do %>
          <i class="fa fa-film"></i>
          Episodewrap 
        <% end %>
        |
        <%= link_to "#" do %>
          FAQ
        <% end %>
        |
        <%= link_to "https://vast-inlet-29334.herokuapp.com/" do %>          
          Developer's Site
        <% end %>
      </div>
    </footer>
    <!-- End of Footer -->
    
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/home.html.erb
<!-- Featured Series scrolling wheel -->
<div class = "container">
  
</div>
<!-- End of scrolling wheel -->

<!-- Front page descriptor -->
<div class = "container">
  <div class = "row">
    <div class = "text-center">
      <h1>Welcome to Episodewrap</h1>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3 text-center">
      <p>Your guide to exploring your favorite TV shows. To begin, select either spoiler-free or spoiler mode from the navigation bar
        above and start exploring!</p>
    </div>
  </div>
</div>
<!-- End of front page descriptor -->

<!-- List of series, alphabetically arranged -->
<div class ="container well">
  <div class ="row">
    <div class = "col-md-3 col-md-offset-1">
      <ul id = "front-page-series-list" class = "text-center" >
        <li>_#_</li>
        <li>_A_</li>
        
        <li>_B_</li>
        <li><%= link_to 'Black Mirror', tvshow_path(id: @blackMirror.id),  class: 'linked-series' %></li>
        <li><%= link_to 'Breaking Bad', tvshow_path(id: @breakingBad.id),  class: 'linked-series' %></li>

        <li>_C_</li>
        <li>_D_</li>
        <li>_E_</li>
        <li>_F_</li>
        <li>_G_</li>
        <li><%= link_to 'Game of Thrones', tvshow_path(id: @gameOfThrones.id),  class: 'linked-series' %></li>
        <li>_H_</li>
      </ul>
    </div>
    <div class = "col-md-3">
      <ul id = "front-page-series-list" class = "text-center" >
        <li>_I_</li>
        <li>_J_</li>
        <li>_K_</li>
        <li>_L_</li>
        <li>_M_</li>
        <li>_N_</li>
        <li>_O_</li>
        <li>_P_</li>
        <li>_Q_</li>
      </ul>
    </div>
    <div class = "col-md-3">
      <ul id = "front-page-series-list" class = "text-center" >
        <li>_R_</li>
        <li>_S_</li>
        <li>_T_</li>
        <li>_U_</li>
        <li>_V_</li>
        <li>_W_</li>
        <li>_X_</li>
        <li>_Y_</li>
        <li>_Z_</li>
      </ul>
    </div>
  </div>
</div>
<!-- End of list of series -->

app/views/tvshows/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3 text-center">
      <h1>Welcome to the <%= Tvshow.find(params[:id]).name %> hub!</h1>
    </div>
  </div>
</div>
<div class = "container">
  <div class = "row">
    <div class = "col-md-2 col-md-offset-1 well">
      
    </div>
    <div class = "col-md-6 well">
      <%= Season.where(tvshow_id: params[:id] ).inspect %>
    </div>
    <div class = "col-md-2 well">
      
    </div>
  </div>
</div>